---
  header_logo_url:
  header_logo_text: The Lampyridae of the World
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about

    - label: Bibliography
      link: /resources/tw/filter/bibliography

    - label: Search DwC
      link: /resources/tw/filter/dwc_otus

    - label: Recent Additions
      link: /recent

    - label: News
      link: /news
